/**
 * AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
 * Source: git tag / SPENTD_VERSION → 1.2.2
 */
export const APP_VERSION = "1.2.2";
export const APP_VERSION_CODE = 10202;
export const AUTHOR = "srineshr1";
export const AUTHOR_URL = "https://github.com/srineshr1";
