#!/usr/bin/env node
/**
 * Sync app version from the nearest git tag (v1.2.1 → 1.2.1).
 * Writes:
 *   - src/version.gen.ts  (runtime UI — always matches the JS bundle)
 *   - package.json version
 *   - app.json expo.version + android.versionCode
 *
 * Run automatically via package.json prestart / preandroid, and in CI before prebuild.
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const repoRoot = path.resolve(root, "../..");

function resolveVersion() {
  const env = process.env.SPENTD_VERSION?.trim();
  if (env) return env.replace(/^v/i, "");

  const refName = process.env.GITHUB_REF_NAME?.trim();
  if (
    refName &&
    (process.env.GITHUB_REF_TYPE === "tag" || /^v\d/.test(refName))
  ) {
    return refName.replace(/^v/i, "");
  }

  for (const cwd of [repoRoot, root, process.cwd()]) {
    try {
      const tag = execSync('git describe --tags --match "v*" --abbrev=0', {
        encoding: "utf8",
        cwd,
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      if (tag) return tag.replace(/^v/i, "");
    } catch {
      /* try next */
    }
  }
  return null;
}

function versionCodeFromSemver(version) {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(version);
  if (!m) return null;
  return Number(m[1]) * 10000 + Number(m[2]) * 100 + Number(m[3]);
}

const version = resolveVersion() || "0.0.0";
const versionCode = versionCodeFromSemver(version) ?? 1;

// 1) Runtime module (what Settings reads — ships with the JS bundle)
const genPath = path.join(root, "src/version.gen.ts");
const gen = `/**
 * AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
 * Source: git tag / SPENTD_VERSION → ${version}
 */
export const APP_VERSION = ${JSON.stringify(version)};
export const APP_VERSION_CODE = ${versionCode};
export const AUTHOR = "srineshr1";
export const AUTHOR_URL = "https://github.com/srineshr1";
`;
fs.mkdirSync(path.dirname(genPath), { recursive: true });
fs.writeFileSync(genPath, gen);

// 2) package.json
const pkgPath = path.join(root, "package.json");
const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
if (pkg.version !== version) {
  pkg.version = version;
  fs.writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
}

// 3) app.json (fallback for tools that don't evaluate app.config.js)
const appJsonPath = path.join(root, "app.json");
const appJson = JSON.parse(fs.readFileSync(appJsonPath, "utf8"));
appJson.expo = appJson.expo || {};
appJson.expo.version = version;
appJson.expo.android = appJson.expo.android || {};
appJson.expo.android.versionCode = versionCode;
fs.writeFileSync(appJsonPath, `${JSON.stringify(appJson, null, 2)}\n`);

console.log(`sync-version: ${version} (versionCode ${versionCode}) → ${path.relative(repoRoot, genPath)}`);
